// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy4yMpttFSe8G9h4Jt7hKphXG8-ZAqwsQ',
    appId: '1:426140031121:web:ef155ef6efcd6fe980c730',
    messagingSenderId: '426140031121',
    projectId: 'f-b-p-29318',
    authDomain: 'f-b-p-29318.firebaseapp.com',
    databaseURL: 'https://f-b-p-29318-default-rtdb.firebaseio.com',
    storageBucket: 'f-b-p-29318.firebasestorage.app',
    measurementId: 'G-1BJ4X1HM1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ92v1SU9Lrb7jRx1Xu7NLO_jWKwknu1w',
    appId: '1:426140031121:android:ecd654053e6fdb1780c730',
    messagingSenderId: '426140031121',
    projectId: 'f-b-p-29318',
    databaseURL: 'https://f-b-p-29318-default-rtdb.firebaseio.com',
    storageBucket: 'f-b-p-29318.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJMAaUWuL4o3twY4rtZbW8Kt2YD1qQwtk',
    appId: '1:426140031121:ios:f841b4a0bd23826580c730',
    messagingSenderId: '426140031121',
    projectId: 'f-b-p-29318',
    databaseURL: 'https://f-b-p-29318-default-rtdb.firebaseio.com',
    storageBucket: 'f-b-p-29318.firebasestorage.app',
    iosBundleId: 'com.example.fbp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJMAaUWuL4o3twY4rtZbW8Kt2YD1qQwtk',
    appId: '1:426140031121:ios:f841b4a0bd23826580c730',
    messagingSenderId: '426140031121',
    projectId: 'f-b-p-29318',
    databaseURL: 'https://f-b-p-29318-default-rtdb.firebaseio.com',
    storageBucket: 'f-b-p-29318.firebasestorage.app',
    iosBundleId: 'com.example.fbp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy4yMpttFSe8G9h4Jt7hKphXG8-ZAqwsQ',
    appId: '1:426140031121:web:ff9f9be198d6679b80c730',
    messagingSenderId: '426140031121',
    projectId: 'f-b-p-29318',
    authDomain: 'f-b-p-29318.firebaseapp.com',
    databaseURL: 'https://f-b-p-29318-default-rtdb.firebaseio.com',
    storageBucket: 'f-b-p-29318.firebasestorage.app',
    measurementId: 'G-D7L1VW4KPQ',
  );
}
